---
windows_hardening:
  system_access: "System Access"
  password_section:
    password_expiry_warning:
      name: 'PasswordExpiryWarning'
      path: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: 14
    password_history_size:
      name: 'PasswordHistorySize'
      value: 5
    maximum_password_age:
      name: 'MaximumPasswordAge'
      value: 90
    minimum_password_age:
      name: 'MinimumPasswordAge'
      value: 1
    minimum_password_length:
      name: 'MinimumPasswordLength'
      value: 8
    password_complexity:
      name: 'PasswordComplexity'
      value: 1
    clear_text_password:
      name: 'ClearTextPassword'
      value: 0
  account_lockout_section:
    lockout_bad_count:
      name: 'LockoutBadCount'
      value: 5
    lockout_duration:
      name: 'LockoutDuration'
      value: 1800
    reset_lockout_count:
      name: 'ResetLockoutCount'
      value: 1800
  auditing_section:
    credential_validation:
      name: 'CredentialValidation'
      value: 'success, failure'
    application_group_management:
      name: 'ApplicationGroupManagement'
      value: 'success, failure'
    computer_account_management:
      name: 'ComputerAccountManagement'
      value: 'success, failure'
    other_account_management_events:
      name: 'OtherAccountManagementEvents'
      value: 'success, failure'
    security_group_management:
      name: 'SecurityGroupManagement'
      value: 'success, failure'
    user_account_management:
      name: 'UserAccountManagement'
      value: 'success, failure'
    plug_and_play_events:
      name: 'PlugandPlayEvents'
      value: 'success'
    process_creation:
      name: 'ProcessCreation'
      value: 'success'
    account_lockout:
      name: 'AccountLockout'
      value: 'success, failure'
    group_membership:
      name: 'GroupMembership'
      value: 'success'
    logoff:
      name: 'Logoff'
      value: 'success'
    logon:
      name: 'Logon'
      value: 'success, failure'
    other_logon_logoff_events:
      name: 'OtherLogon/LogoffEvents'
      value: 'success, failure'
    special_logon:
      name: 'SpecialLogon'
      value: 'success'
    removable_storage:
      name: 'RemovableStorage'
      value: 'success, failure'
    audit_policy_change:
      name: 'AuditPolicyChange'
      value: 'success, failure'
    authentication_policy_change:
      name: 'AuthenticationPolicyChange'
      value: 'success'
    authorization_policy_change:
      name: 'AuthorizationPolicyChange'
      value: 'success'
    sensitive_privilege_use:
      name: 'SensitivePrivilegeUse'
      value: 'success, failure'
    other_system_events:
      name: 'OtherSystemEvents'
      value: 'success, failure'
    security_state_change:
      name: 'SecurityStateChange'
      value: 'success'
    security_system_extension:
      name: 'SecuritySystemExtension'
      value: 'success, failure'
    system_integrity:
      name: 'SystemIntegrity'
      value: 'success, failure'
  registry_fixes_section:
    dont_display_last_user_name:
      name: 'DontDisplayLastUserName'
      path: 'HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System'
      value: '1'
      type: 'dword'
    screen_saver_is_secure:
      name: 'ScreenSaverIsSecure'
      path: 'HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop'
      value: '1'
      type: 'string'
