---
- name: Perform Password Hardening
  include_tasks: password_section.yml
  when: "'Base-Profile' in profile"

#- name: Perform Account Lockout Hardening
#  include_tasks: account_lockout_section.yml
 # when: "'Base-Profile' in profile"

#- name: Perform Auditing Hardening
#  include_tasks: auditing_section.yml
#  when: "'Base-Profile' in profile"

- name: Perform Registry Fixes
  include_tasks: registry_fixes_section.yml
  when: "'Base-Profile' in profile"
